name: login
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.2"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.0
  flutter_map: ^2.2.0
  flutter_riverpod: ^2.0.2
  get: ^4.6.5
  http: ^0.13.5
  latlong2: ^0.8.1
  shared_preferences: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/pic/
    - assets/box/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
