// This file is "main.dart"
// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
    @JsonKey(name: 'nama_depan') required String namaDepan,
    @JsonKey(name: 'nama_belakang') required String namaBelakang,
    required String email,
    @JsonKey(name: 'tanggal_lahir') required String tanggalLahir,
    @JsonKey(name: 'jenis_kelamin') required String jenisKelamin,
    required String password,
    @JsonKey(name: 'foto_profil') required String fotoProfil,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) =>
      _$UserModelFromJson(json);
}
